export const thisIsFor: string[] = [
  "This", "is", "for", "all", "my", "ladies", "who", "don't", "get", "hyped", "enough", "ladies",
  "If", "you've", "been", "done", "wrong,", "then", "this", "your", "song,", "so", "turn", "it", "up",
  "it", "up", "for", "me,", "uh,", "uh",
  "I", "wanna", "go", "where", "the", "baddest", "girls", "are", "from", "uh,", "uh",
  "Might", "be", "another", "planet",
  "Maybe,", "that's", "where", "Mother", "Nature", "made", "me",
  "Something", "about", "that", "water", "tastes", "like", "fun", "yeah,", "yeah",
  "My", "girls", "make", "it", "rain", "confetti,", "sweet", "on", "your", "tongue",
  "I'm", "outside", "your", "door,", "so", "let's", "go,", "don't", "let", "that",
  "beep,", "beep,", "beep", "have", "you", "feeling", "low,", "when", "you're", "grown,", "you", "got", "the",
  "key,", "key,", "keys,", "you", "got", "it", "you", "already", "know,", "when", "it", "shows", "tonight",
  "It's", "you", "and", "me,", "how", "it", "should", "be",
  "This", "is", "for", "all", "my", "ladies", "who", "don't", "get", "hyped", "enough",
  "If", "you've", "been", "done", "wrong,", "then", "this", "your", "song,", "so", "turn", "it", "up",
  "One", "time", "for", "all", "my", "ladies,", "you're", "lookin'", "good", "as", "what",
  "So", "tell", "'em,", "\"Bye,", "bye,\"", "'cause", "it's", "your", "time", "to", "turn", "it", "up",
  "Thi-thi-this", "for", "the", "girls", "with", "that", "light", "inside",
  "They", "spin", "around", "you", "like", "satellite",
  "Yeah,", "you", "the", "baddest,", "all", "day", "and", "night",
  "I'll", "give", "you", "flowers", "'til", "the", "end", "of", "time",
  "this", "your", "moment,", "go", "get", "it",
  "forget", "that", "boy,", "and", "don't", "sweat", "it",
  "I'll", "always", "be", "your", "ride", "or", "die,", "so",
  "I'm", "outside", "your", "door,", "so", "let's", "go,", "don't", "let", "that",
  "beep,", "beep,", "beep", "have", "you", "feeling", "low,", "when", "you're", "grown,", "you", "got", "the",
  "key,", "key,", "keys", "you", "already", "know,", "when", "it", "shows", "tonight",
  "It's", "you", "and", "me,", "how", "it", "should", "be",
  "This", "is", "for", "all", "my", "ladies", "who", "don't", "get", "hyped", "enough",
  "If", "you've", "been", "done", "wrong,", "then", "this", "your", "song,", "so", "turn", "it", "up",
  "One", "time", "for", "all", "my", "ladies", "you're", "lookin'", "good", "as", "what",
  "So", "tell", "'em,", "\"Bye,", "bye,\"", "'cause", "it's", "your", "time", "to", "turn", "it", "up",
  "All", "my", "ladies", "now", "now,", "now,", "ow,", "ow,", "ow,", "oh",
  "Let's", "get", "down", "let's", "get)", "come", "on,", "dip", "your", "hip", "into", "it",
  "All", "my", "ladies", "now", "now,", "now,", "ow,", "ow,", "ow", "ladies", "now",
  "Let's", "get", "down", "down", "come", "on,", "dip", "your", "hip", "into", "it",
  ",", "now,", "ow,", "ow,", "ow",
  "This", "is", "for", "my", "ladies", "let's", "get", "down,", "come", "on,", "dip", "your", "hip", "into", "it",
  "Ladies", "all", "my", "ladies", "now", "now,", "now,", "ow,", "ow,", "ow",
  "This", "is", "for", "my", "ladies", "let's", "get", "down,", "come", "on,", "dip", "your", "hip", "into", "it"
];
